timeout: 0
quiet: yes
interface_branding: Luna OS

default_entry: 1

/Luna OS
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: console=framebuffer,serial0 root=none
    resolution: 1024x768x32
